;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Weapon.Reload",NewTagName="Weapon.Reloading")
+GameplayTagList=(Tag="Aim.IronSights",DevComment="")
+GameplayTagList=(Tag="Aim.Sights",DevComment="")
+GameplayTagList=(Tag="Ammo.Heavy",DevComment="")
+GameplayTagList=(Tag="Ammo.Medium",DevComment="")
+GameplayTagList=(Tag="Ammo.Small",DevComment="")
+GameplayTagList=(Tag="Attachment.Barrel",DevComment="")
+GameplayTagList=(Tag="Attachment.Grip",DevComment="")
+GameplayTagList=(Tag="Attachment.Sights",DevComment="")
+GameplayTagList=(Tag="HitScan",DevComment="")
+GameplayTagList=(Tag="Movement.Crouched",DevComment="")
+GameplayTagList=(Tag="Shooting.CanFire",DevComment="")
+GameplayTagList=(Tag="Shooting.FireMode.Automatic",DevComment="")
+GameplayTagList=(Tag="Shooting.FireMode.Burst",DevComment="")
+GameplayTagList=(Tag="Shooting.FireMode.SemiAutomatic",DevComment="")
+GameplayTagList=(Tag="Shooting.isFiring",DevComment="")
+GameplayTagList=(Tag="Weapon.CanFire",DevComment="")
+GameplayTagList=(Tag="Weapon.CanReload",DevComment="")
+GameplayTagList=(Tag="Weapon.CanSwitch",DevComment="")
+GameplayTagList=(Tag="Weapon.Reloading",DevComment="")
+GameplayTagList=(Tag="Weapon.Slot1",DevComment="")
+GameplayTagList=(Tag="Weapon.Slot2",DevComment="")
+GameplayTagList=(Tag="Weapon.Slot3",DevComment="")
+GameplayTagList=(Tag="Weapon.SlotsFull",DevComment="")

